### ISSUE TITLE
Implement JavaScript Classes In Pure ES6 Injected At Page Load Time

### ISSUE THREAD

**Issue by lots0logs** [Antergos/web-greeter#77]

**Comment by NoiSek** [comment]
I had no idea webkit actually supported native ES6 already, just read about it for the first time. Guess I missed that memo.

Does this mean the API changes, or is this still going to be backwards compatible? If the former, it'd be neat to have some of those calls return promises instead of having to define `window.foo` defaults.

**Comment by lots0logs** [comment]
Yes WebKit has had ES6 support for a while now. The default them was rewritten in ES6 over a year ago. I had not considered making changes to the API. If we do decide to make changes, we will ensure that its backwards compatible. Typically we'll mark things as deprecated for a few releases before removing them (to give theme developers time to update their themes.)

**Comment by lots0logs** [comment]
Decided to hold off on this for now. It looks like there may soon(ish) be an official gobject api we can use for this.
